[Feature] Create People Listing
vinibr3/Buy-Here pull request #42
Opened 2018-10-01 20:47 UTC by raphaelsattler

Add people list feature and its tests.

2018-10-01 21:05 UTC, kaiomagalhaes requested changes

2018-10-01 21:05 UTC, kaiomagalhaes commented on app/assets/stylesheets/custom.scss.css
> +.pagination {
please change the name of this file. `custom` doesn't mean anything. Can you imagine having a file with 1000+ lines? no thanks.

Create one file for the pagination, and then one for each  shared/page

2018-10-02 16:47 UTC, kaiomagalhaes submitted a review, later dismissed

2018-10-02 16:57 UTC, RodrigoNM commented on app/views/people/_list.html.erb
> +            <th>Email</th>
Why are you not using I18n here?

2018-10-02 18:48 UTC, kaiomagalhaes approved these changes

2018-10-02 20:22 UTC, RodrigoNM approved these changes

2018-10-02 20:22 UTC, merged