[Feature] user login
vinibr3/Buy-Here pull request #43
Opened 2018-10-02 13:43 UTC by vinibr3

Create user login and navbar.

2018-10-02 17:23 UTC, kaiomagalhaes requested changes

2018-10-02 17:23 UTC, kaiomagalhaes commented on app/controllers/sessions_controller.rb
> +    def session_params
please name it `valid_params` this way you don't need to have a params name for each controller

2018-10-02 17:23 UTC, kaiomagalhaes commented on spec/spec_helper.rb
> +  # config.include Support::Features::SessionHelpers, type: :feature
why is this commented code here?

2018-10-02 17:23 UTC, kaiomagalhaes commented on spec/support/feature.rb
> +RSpec.configure do |config|
shouldn't the filename be `features`?

2018-10-02 20:29 UTC, kaiomagalhaes submitted a review, later dismissed

2018-10-04 12:54 UTC, RodrigoNM submitted a review, later dismissed

2018-10-04 14:49 UTC, matcheus requested changes

2018-10-04 14:49 UTC, matcheus commented on app/views/sessions/new.html.erb
> +  <%end%>
This tag is with wrong identation and should have spaces between "<%" and "end", like this "<% end %>"

2018-10-04 14:49 UTC, matcheus commented on app/views/sessions/new.html.erb
> +</div>
This file has errors.

2018-10-04 14:49 UTC, matcheus commented on app/views/users/show.html.erb
> +<h1> Hello </h1>
This file has a error too.

2018-10-04 14:49 UTC, matcheus commented on spec/features/user_sign_in_spec.rb
> +  it "when user log out" do
If you are doing acceptance tests with Capybara you should use "scenario" here too, instead of "it"

2018-10-04 14:51 UTC, matcheus requested changes

2018-10-04 14:51 UTC, matcheus commented on app/views/layouts/_navbar.html.erb
> +</nav>
This file have errors too.

2018-10-04 18:26 UTC, matcheus commented on app/views/sessions/new.html.erb
> +  <div class="col-md-6 offset-md-3">
Identation of this file is wrong

2018-10-04 20:21 UTC, matcheus approved these changes

2018-10-05 12:05 UTC, RodrigoNM approved these changes

2018-10-05 12:05 UTC, merged