[Feature] Search People
vinibr3/Buy-Here pull request #44
Opened 2018-10-02 21:16 UTC by raphaelsattler

Create search people feature and its tests

2018-10-02 21:44 UTC, RodrigoNM commented on app/views/people/index.html.erb
> +          <%= f.collection_select :profile_name_cont, Profile.all, :name, :name, { include_blank: true }, { class: "btn-sm" } %>
This should be a helper.

2018-10-03 14:57 UTC, kaiomagalhaes requested changes

2018-10-03 14:57 UTC, kaiomagalhaes commented on app/assets/stylesheets/table.scss.css
> +  color: #FFFFFF !important;
Never use !important. If you need it to be more specific then create an id

2018-10-03 14:57 UTC, kaiomagalhaes commented on app/controllers/person_controller.rb
> +    @people = @q.result.includes(:profile, :buy_intention).paginate(page: params[:page], per_page: 5)
use the safe params here

2018-10-03 18:30 UTC, kaiomagalhaes requested changes

2018-10-03 18:30 UTC, kaiomagalhaes commented on app/assets/stylesheets/form_filter.scss.css
> +  background-color: #6577FF !important;
please avoid !Important, instead use `id`

2018-10-03 18:30 UTC, kaiomagalhaes commented on app/assets/stylesheets/form_filter.scss.css
> +  background-color: #6577FF !important;
please avoid !Important, instead use id

2018-10-03 18:39 UTC, kaiomagalhaes approved these changes

2018-10-03 21:23 UTC, Heirian approved these changes

2018-10-03 21:23 UTC, merged